### ISSUE TITLE
Theme agiliq is missing.

### ISSUE THREAD

**Issue by edthedev** [agiliq/django-design-patterns#11]
make html
sphinx-build -b html -d build/doctrees   source buil
d/html
Running Sphinx v1.1.3
loading pickled environment... done

Theme error:
no theme named 'agiliq' found (missing theme.conf?)
make: **\* [html] Error 1

**Comment by DaveJ61** [comment]
This still does not work. The themes are already included anyway. However, I went ahead and added as above and get the same error.
